// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.WebApi.Data.Migrations
{
    [DbContext(typeof(BackendDB))]
    partial class BackendDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Backend.WebApi.Data.Models.Name", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("NAME_ID");

                    b.Property<string>("AuthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME_AUTH");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME_FIRST");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME_LAST");

                    b.HasKey("Id");

                    b.ToTable("NAME", (string)null);
                });

            modelBuilder.Entity("Backend.WebApi.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SB_ID");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("SB_PASSWORT");

                    b.Property<int>("NameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SB_NAME_ID");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SB_REMEMBERME");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("SB", (string)null);
                });

            modelBuilder.Entity("Backend.WebApi.Data.Models.User", b =>
                {
                    b.HasOne("Backend.WebApi.Data.Models.Name", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
